[package]
name = "stream-log-client"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
console_error_panic_hook = "0.1.7"
futures = "0.3.21"
mogwai = "0.5.3"
gloo-net = { version = "0.1.0", features = ["websocket"] }
stream-log-shared = { path = "../shared" }
serde = "1.0.136"
serde_json = "1.0.79"
wasm-bindgen = "0.2.80"

[dependencies.web-sys]
version = "0.3.56"
features = [
	"FormData",
	"HtmlFormElement",
	"HtmlInputElement",
	"Location",
	"Storage",
	"Url",
	"Window"
]