[package]
name = "stream-log-client"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
chrono = { version = "0.4.24", features = ["wasmbind"] }
console_error_panic_hook = "0.1.7"
contrast = "0.1.0"
futures = "0.3.28"
gloo-net = { version = "0.2.6", features = ["websocket"] }
log = "0.4.17"
rgb = "0.8.36"
serde = "1.0.162"
serde_json = "1.0.96"
stream-log-shared = { path = "../shared" }
sycamore = { version = "0.8.2", features = ["suspense"] }
sycamore-router = "0.8.0"
wasm-bindgen = "0.2.84"
wasm-logger = "0.2.0"

[dependencies.web-sys]
version = "0.3.61"
features = [
	"Event",
	"EventTarget",
	"HtmlButtonElement",
	"HtmlElement",
	"HtmlInputElement",
	"HtmlSpanElement",
	"Node",
	"Url"
]