[package]
name = "stream-log-server"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-std = { version = "1.11.0", features = ["attributes"] }
cuid = "1.2.0"
diesel = { version = "1.4.4", features = ["postgres"] }
diesel-derive-enum = { version = "1.1.2", features = ["postgres"] }
knuffel = "2.0.0"
miette = { version = "4.5.0", features = ["fancy"] }
serde_json = "1.0.79"
stream-log-shared = { path = "../shared" }
tide = "0.16.0"
tide-openidconnect = "0.1.0"
tide-websockets = "0.4.0"