[package]
name = "stream-log-server"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-std = { version = "1.11.0", features = ["attributes"] }
knuffel = "2.0.0"
miette = { version = "4.2.1", features = ["fancy"] }
stream-log-shared = { path = "../shared" }
tide = "0.16.0"
tide-websockets = "0.4.0"