[package]
name = "stream-log-server"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
chrono = "0.4.24"
clap = { version = "4.2.7", features = ["derive"] }
cuid2 = "0.1.0"
diesel = { version = "2.0.4", features = ["chrono", "postgres"] }
diesel_migrations = "2.0.0"
diesel-derive-enum = { version = "2.0.1", features = ["postgres"] }
erased-serde = "0.3.25"
futures = "0.3.28"
knuffel = "3.2.0"
miette = { version = "5.8.0", features = ["fancy"] }
rgb = "0.8.36"
serde_json = "1.0.96"
stream-log-shared = { path = "../shared" }
tide = "0.16.0"
tide-openidconnect = "0.1.0"
tide-websockets = "0.4.0"