[package]
name = "stream-log-server"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
chrono = "0.4.23"
clap = { version = "4.1.4", features = ["derive"] }
cuid = "1.3.1"
diesel = { version = "2.0.3", features = ["chrono", "postgres"] }
diesel_migrations = "2.0.0"
diesel-derive-enum = { version = "2.0.0-rc.0", features = ["postgres"] }
futures = "0.3.26"
knuffel = "2.0.0"
miette = { version = "4.7.1", features = ["fancy"] }
rgb = "0.8.35"
serde_json = "1.0.93"
stream-log-shared = { path = "../shared" }
tide = "0.16.0"
tide-openidconnect = "0.1.0"
tide-websockets = "0.4.0"