[package]
name = "stream-log-shared"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }