[package]
name = "stream-log-shared"
authors = ["Jacob Riddle (ElementalAlchemist) <ElementAlchemist7@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
rgb = { version = "0.8.35", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }